### ISSUE TITLE
Allows you to see through walls

### ISSUE THREAD

**Issue by SebastianS13** [MaximumADHD/Character-Realism#23]
**When a player goes up to a wall in the game and looks down they can see what's behind the room and since the scripts are pretty complex I don't know how to edit it accordingly**

![RobloxScreenShot20230127_134758809](https://user-images.githubusercontent.com/50264212/215180892-283e7a0e-4538-42f5-949a-933c6eac08d5.png)
 https://user-images.githubusercontent.com/50264212/215181078-f8b80cff-e9ae-4692-a12d-2403790bb3f4.mp4

**Comment by IlikeFerrets** [comment]
Hey, since this issue is caused, because of the animation that lets the player's head go through walls/objects you could just enable "CanCollide" for the character's head.
This should fix the issue
