### ISSUE TITLE
Character is glitcy

### ISSUE THREAD

**Issue by Inactiv** [MaximumADHD/Character-Realism#24]
Hello, I inputted this character realism scripts into my ROBLOX game (without rojo) and for some reason, the characters arms go inwards

![image_2023-05-05_182003398](https://user-images.githubusercontent.com/132720700/236587939-6a6c30c2-38a5-4b6f-b959-454521d10c51.png)

**Comment by Inactiv** [comment]
please let me know if there is any fix for this (RIG is R15)

**Comment by GOSPODNYY** [comment]
disable retargeting setting in workspace properties

**Comment by MaximumADHD** [comment]
Yep, it’s related to retargeting. Not realism related.
